#! /bin/sh

#autostart apps
pgrep -x sxhkd > /dev/null || sxhkd &

# gtk themes and term colorsheme
#cp -r ~/Public/theme\ and\ icons/bsp/.gtkrc-2.0 ~/ &
#cp -r ~/Public/theme\ and\ icons/bsp/settings.ini ~/.config/gtk-3.0/ &
xrdb merge ~/.Xresources &
xsetroot -cursor_name left_ptr & #changing cursor
picom &

# polybar 
#cp -r ~/Public/poly/bsp/polybar ~/.config/ &
~/.config/polybar/launch.sh &

#wallpaper and nvim
feh --bg-fill --randomize ~/.backgrounds/themewall/*
#del .config/nvim && cp -r ~/Public/nvim_confs/base/nvim ~/.config/ &

# workspaces 
bspc monitor -d 1 2 3 4 5 6 7 8 9

#bspc config focus_follows_pointer true

bspc config top_padding 35

# borders
bspc config focused_border_color "#353b45"
bspc config normal_border_color  "#282c34"
bspc config border_width 2
bspc config borderless_monocle true

# rules
bspc rule -a discord desktop='^4' state=tiled follow=false
bspc rule -a qBittorrent desktop='^5' state=tiled follow=true
bspc rule -a vlc desktop='^6' state=tiled follow=true
bspc rule -a Zathura state=tiled
bspc rule -a Pcmanfm desktop='^7' state=tiled follow=true
#bspc rule -a Android Emulator - Pixel_4a_API_30:5554 state=floating follow=false # doesn't work for now
#bspc rule -a Emulator state=floating follow=false

# gaps 
bspc config gapless_monocle false
bspc config window_gap 12
bspc config split_ratio 0.59
bspc config ignore_ewmh_focus true
